version: '3.3'

services:
    php-fpm:
        build:
            context: ./php
        ports:
            - 9000:9000
        volumes:
            - ./../:/var/www/html
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - ${DOCKERIZED_NETWORK}

    nginx:
        image: nginx:1.13.8
        volumes:
            - ./../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.mage.conf.sample:/etc/nginx/conf.d/nginx.mage.conf.sample
            - ./certs:/etc/nginx/certs
        depends_on:
            - php-fpm
        environment:
            SERVER_NAME: ${SERVER_NAME}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=HostHeader(`${SERVER_NAME}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.entrypoints=websecure"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.rule=HostHeader(`${SERVER_NAME}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx-secure.tls=true"
        networks:
            - ${DOCKERIZED_NETWORK}

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        depends_on:
            - php-fpm
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${DOCKERIZED_NETWORK}"
            - "traefik.http.routers.mysql.rule=Host(`db-${SERVER_NAME}`)"
            - "traefik.port=3306"
        networks:
            - ${DOCKERIZED_NETWORK}

networks:
    dockerized:
        external: true
